# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/diary56x/frontend"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
